trigger:
- main

pool:
  vmImage: 'macOS-12'

steps:

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: '**/*.xcworkspace' # Update to match the location of your workspace
    xcodeVersion: 'default' # Options: 10, 11, 12, 13, 14, default, specifyPath
    packageApp: true
    signingOption: 'manual'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)/App'
    Contents: '**/*'
    targetFolder: '$(build.artifactStagingDirectory)'
     
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'gci env:* | sort-object name | Format-Table -AutoSize | Out-File $env:BUILD_ARTIFACTSTAGINGDIRECTORY/environment-variables.txt'

- task: DownloadBuildArtifacts@0 # downloads a single build artifact named 'drop' from the current build and places it in the directory specified by $(System.ArtifactsDirectory).
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'   


